name = "bokbup-app"
compatibility_date = "2026-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "bokbup-stats"
database_id = "1746a399-08f7-469b-9f1c-0d40a50aaa07"
